[testenv:bootstrap]
deps =
    jinja2
    tox
skip_install = true
commands =
    python ci/bootstrap.py --no-env
passenv =
    *

[tox]
envlist =
    clean,
    check,
    docs,
    {py311,py312,py313,py314},
    report
ignore_basepython_conflict = true
skip_missing_interpreters = true

[testenv]
basepython =
    py311: {env:TOXPYTHON:python3.11}
    py312: {env:TOXPYTHON:python3.12}
    py313: {env:TOXPYTHON:python3.13}
    py314: {env:TOXPYTHON:python3.14}
    {clean,check,docs,report}: {env:TOXPYTHON:python3.13}
setenv =
    PYTHONPATH={toxinidir}/tests
    PYTHONUNBUFFERED=yes
passenv =
    *
usedevelop = false
deps =
    pytest
    pytest-cov
commands =
    {posargs:pytest --basetemp {envtmpdir} --cov {envsitepackagesdir}/porkbun_api_cli --cov-append --cov-report term-missing -vv}

[testenv:check]
deps =
    ruff==0.16.6
    ty==0.0.79
    types-PyYAML
    types-requests
    docutils
    check-manifest
    readme-renderer
    pygments
usedevelop = true
commands =
    ruff check .
    ruff format --check --diff .
    ty check src/porkbun_api_cli
    python -m readme_renderer README.rst -o /dev/null
    check-manifest .

[testenv:docs]
usedevelop = true
deps =
    -r{toxinidir}/docs/requirements.txt
commands =
    sphinx-build {posargs:-E} -b html docs dist/docs
    sphinx-build -b linkcheck docs dist/docs

[testenv:report]
deps =
    coverage
skip_install = true
commands =
    coverage report -i
    coverage xml -i

[testenv:clean]
commands = coverage erase
skip_install = true
