name: build
on: [push, pull_request]
jobs:
  test_n_build_wheel:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'check'
            python: '3.13'
            toxpython: 'python3.13'
            tox_env: 'check'
            os: 'ubuntu-latest'
          - name: 'docs'
            python: '3.13'
            toxpython: 'python3.13'
            tox_env: 'docs'
            os: 'ubuntu-latest'
          - name: 'py311 (ubuntu/x86_64)'
            python: '3.11'
            toxpython: 'python3.11'
            python_arch: 'x64'
            tox_env: 'py311'
            os: 'ubuntu-latest'
          - name: 'py311 (windows/AMD64)'
            python: '3.11'
            toxpython: 'python3.11'
            python_arch: 'x64'
            tox_env: 'py311'
            os: 'windows-latest'
          - name: 'py311 (macos/arm64)'
            python: '3.11'
            toxpython: 'python3.11'
            python_arch: 'arm64'
            tox_env: 'py311'
            os: 'macos-latest'
          - name: 'py312 (ubuntu/x86_64)'
            python: '3.12'
            toxpython: 'python3.12'
            python_arch: 'x64'
            tox_env: 'py312'
            os: 'ubuntu-latest'
          - name: 'py312 (windows/AMD64)'
            python: '3.12'
            toxpython: 'python3.12'
            python_arch: 'x64'
            tox_env: 'py312'
            os: 'windows-latest'
          - name: 'py312 (macos/arm64)'
            python: '3.12'
            toxpython: 'python3.12'
            python_arch: 'arm64'
            tox_env: 'py312'
            os: 'macos-latest'
          - name: 'py313 (ubuntu/x86_64)'
            python: '3.13'
            toxpython: 'python3.13'
            python_arch: 'x64'
            tox_env: 'py313'
            os: 'ubuntu-latest'
          - name: 'py313 (windows/AMD64)'
            python: '3.13'
            toxpython: 'python3.13'
            python_arch: 'x64'
            tox_env: 'py313'
            os: 'windows-latest'
          - name: 'py313 (macos/arm64)'
            python: '3.13'
            toxpython: 'python3.13'
            python_arch: 'arm64'
            tox_env: 'py313'
            os: 'macos-latest'
          - name: 'py314 (ubuntu/x86_64)'
            python: '3.14'
            toxpython: 'python3.14'
            python_arch: 'x64'
            tox_env: 'py314'
            os: 'ubuntu-latest'
          - name: 'py314 (windows/AMD64)'
            python: '3.14'
            toxpython: 'python3.14'
            python_arch: 'x64'
            tox_env: 'py314'
            os: 'windows-latest'
          - name: 'py314 (macos/arm64)'
            python: '3.14'
            toxpython: 'python3.14'
            python_arch: 'arm64'
            tox_env: 'py314'
            os: 'macos-latest'
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.python_arch }}
    - name: install dependencies
      run: |
        python -mpip install --progress-bar=off -r ci/requirements.txt
        tox --version
    - name: regular build and test
      env:
        TOXPYTHON: '${{ matrix.toxpython }}'
      run: >
        tox -e ${{ matrix.tox_env }} -v

  coverage:
    runs-on: ubuntu-latest
    environment: codecov
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up Python 3.13
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -mpip install --progress-bar=off -r ci/requirements.txt
          tox --version
      - name: Run tests and collect coverage
        run: tox -e py313,report -v
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          verbose: true

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Build sdist
        run: |
          python -mpip install --progress-bar=off pipx
          pipx run build --sdist

      - uses: actions/upload-artifact@v7
        with:
          path: dist/*.tar.gz

  upload_pypi:
    needs: [test_n_build_wheel, build_sdist]
    runs-on: ubuntu-latest
    environment: pypi
    # upload to PyPI on every tag starting with 'v'
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    # alternatively, to publish when a GitHub Release is created, use the following rule:
    # if: github.event_name == 'release' && github.action == 'published'
    steps:
      - uses: actions/download-artifact@v8
        with:
          # unpacks default artifact into dist/
          # if `name: artifact` is omitted, the action will create extra parent dir
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PIPY_TEST_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
